import { PlatformShell, type Language } from "@/components/PlatformShell";
import { trpc } from "@/lib/trpc";
import { Activity, ClipboardCheck, FileCheck2, UsersRound } from "lucide-react";

export default function AdminAnalyticsPage({ language, onLanguageChange }: { language: Language; onLanguageChange: (value: Language) => void }) {
  const copy = (en: string, bn: string) => language === "bn" ? bn : en;
  const analytics = trpc.learning.adminAnalytics.useQuery();
  const data = analytics.data;
  const cards = [
    { icon: UsersRound, label: copy("Registered learners", "নিবন্ধিত শিক্ষার্থী"), value: data?.totalUsers, detail: copy(`${data?.activeUsersLast7Days ?? 0} active in the last 7 days`, `গত ৭ দিনে ${data?.activeUsersLast7Days ?? 0} জন সক্রিয়`) },
    { icon: Activity, label: copy("Completed attempts", "সম্পন্ন অ্যাটেম্পট"), value: data?.completedAttempts, detail: data?.completionRate === null || data?.completionRate === undefined ? copy("No attempts started yet", "এখনও কোনো অ্যাটেম্পট শুরু হয়নি") : copy(`${data.completionRate}% completion rate`, `${data.completionRate}% সম্পন্ন হার`) },
    { icon: FileCheck2, label: copy("Published questions", "প্রকাশিত প্রশ্ন"), value: data?.publishedQuestions, detail: copy("Source-linked student capacity", "সোর্স-লিংকড শিক্ষার্থী সক্ষমতা") },
    { icon: ClipboardCheck, label: copy("Awaiting human review", "হিউম্যান রিভিউয়ের অপেক্ষায়"), value: data?.questionsAwaitingReview, detail: copy("Source-mapped intake items", "সোর্স-ম্যাপড ইনটেক আইটেম") },
  ];
  return <PlatformShell language={language} onLanguageChange={onLanguageChange}><main className="mx-auto max-w-6xl space-y-6"><section className="rounded-[28px] bg-[#071d33] p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#7ce3d1]">ADMIN ANALYTICS</p><h1 className="mt-2 font-display text-3xl font-extrabold">{copy("Live platform summary", "লাইভ প্ল্যাটফর্ম সারাংশ")}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">{copy("Read-only aggregates from persisted learner activity and the review pipeline. This view intentionally excludes private messages, IP addresses, payment evidence, and unsupported revenue forecasts.", "সংরক্ষিত শিক্ষার্থী অ্যাক্টিভিটি ও রিভিউ পাইপলাইন থেকে রিড-অনলি সারাংশ। এই ভিউতে ব্যক্তিগত মেসেজ, আইপি অ্যাড্রেস, পেমেন্ট এভিডেন্স বা সমর্থনহীন রাজস্ব পূর্বাভাস নেই।")}</p></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ icon: Icon, label, value, detail }) => <article key={label} className="rounded-[24px] bg-white p-5 shadow-sm"><span className="grid size-10 place-items-center rounded-xl bg-[#e9fbf7] text-[#087b6c]"><Icon size={19} /></span><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-2 font-display text-3xl font-extrabold text-[#071d33]">{analytics.isLoading ? "…" : value ?? 0}</p><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></article>)}</section><p className="rounded-2xl border border-[#d8e4ff] bg-[#f4f7ff] p-4 text-sm leading-6 text-[#315bb3]">{copy("For question-level review and release actions, use the existing Content Governance workspace. Analytics never bypasses the source-review gate.", "প্রশ্নভিত্তিক রিভিউ ও রিলিজের জন্য বিদ্যমান কনটেন্ট গভর্ন্যান্স ওয়ার্কস্পেস ব্যবহার করুন। অ্যানালিটিক্স কখনো সোর্স-রিভিউ গেট বাইপাস করে না।")}</p></main></PlatformShell>;
}
