import { PlatformShell, type Language } from "@/components/PlatformShell";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { TodaysStudyGuide } from "@/components/TodaysStudyGuide";
import { BarChart3, Bell, BookOpenCheck, CheckCircle2, LockKeyhole, Play, ShieldCheck, Sparkles, Trophy } from "lucide-react";
import { useLocation } from "wouter";

type LearningSurface = "home" | "practice" | "exams" | "tutor" | "progress" | "studyPlan" | "mistakes" | "bookmarks" | "settings";
type Copy = { en: string; bn: string; detailEn: string; detailBn: string };
const learningSurfaceCopy: Record<LearningSurface, Copy> = {
  home: { en: "Build a learning record you can trust.", bn: "বিশ্বাসযোগ্য লার্নিং রেকর্ড তৈরি করো।", detailEn: "MCQ GURU shows content and performance only when it exists in your real learning record.", detailBn: "MCQ GURU শুধু তখনই কনটেন্ট ও পারফরম্যান্স দেখায়, যখন তা তোমার আসল লার্নিং রেকর্ডে থাকে।" },
  practice: { en: "Practice opens when reviewed questions are published.", bn: "রিভিউ করা প্রশ্ন প্রকাশিত হলেই প্র্যাকটিস চালু হবে।", detailEn: "Start an approved, source-linked practice run only after questions pass the controlled release gate.", detailBn: "প্রশ্ন কন্ট্রোলড রিলিজ গেট পাস করার পরই অনুমোদিত, সোর্স-লিংকড প্র্যাকটিস শুরু করো।" },
  exams: { en: "Exams become available when verified patterns and questions are ready.", bn: "যাচাইকৃত প্যাটার্ন ও প্রশ্ন প্রস্তুত হলেই এক্সাম পাওয়া যাবে।", detailEn: "No model exam is presented as official before its pattern and question set are verified.", detailBn: "প্যাটার্ন ও প্রশ্নসেট যাচাই হওয়ার আগে কোনো মডেল এক্সামকে অফিসিয়াল হিসেবে দেখানো হয় না।" },
  tutor: { en: "The Tutor cites approved evidence when it is available.", bn: "প্রমাণ থাকলে টিউটর অনুমোদিত সোর্স উদ্ধৃত করে।", detailEn: "A source-grounded answer requires indexed approved material; unsupported answers are never invented.", detailBn: "সোর্স-গ্রাউন্ডেড উত্তরের জন্য ইনডেক্স করা অনুমোদিত ম্যাটেরিয়াল প্রয়োজন; প্রমাণহীন উত্তর কখনো বানানো হয় না।" },
  progress: { en: "Progress grows from submitted attempts.", bn: "জমা দেওয়া অ্যাটেম্পট থেকেই প্রগ্রেস তৈরি হয়।", detailEn: "Accuracy, marks, and streaks appear only after you complete real source-linked practice.", detailBn: "আসল সোর্স-লিংকড প্র্যাকটিস শেষ করার পরই নির্ভুলতা, মার্কস ও স্ট্রিক দেখা যায়।" },
  studyPlan: { en: "Your study plan begins with your real learning activity.", bn: "তোমার আসল লার্নিং অ্যাক্টিভিটি থেকেই স্টাডি প্ল্যান শুরু হয়।", detailEn: "MCQ GURU will not invent a schedule or weak topic before content and attempts exist.", detailBn: "কনটেন্ট ও অ্যাটেম্পট না থাকলে MCQ GURU কৃত্রিম শিডিউল বা দুর্বল টপিক তৈরি করবে না।" },
  mistakes: { en: "Your Mistake Vault is created by incorrect submitted answers.", bn: "ভুল জমা দেওয়া উত্তর থেকেই তোমার মিসটেক ভল্ট তৈরি হয়।", detailEn: "There are no sample mistakes here; every saved item comes from a real attempt.", detailBn: "এখানে কোনো নমুনা ভুল নেই; প্রতিটি সেভ করা আইটেম আসল অ্যাটেম্পট থেকে আসে।" },
  bookmarks: { en: "Bookmarks appear when you save real published questions.", bn: "আসল প্রকাশিত প্রশ্ন সেভ করলেই বুকমার্ক দেখা যাবে।", detailEn: "Saved-question lists are never prefilled with examples.", detailBn: "সেভ করা প্রশ্নের তালিকা কখনো উদাহরণ দিয়ে ভরা হয় না।" },
  settings: { en: "Your account preferences are ready when you sign in.", bn: "সাইন ইন করলেই তোমার অ্যাকাউন্ট পছন্দসমূহ প্রস্তুত।", detailEn: "Manage your profile and notifications with a secure account session.", detailBn: "নিরাপদ অ্যাকাউন্ট সেশনের মাধ্যমে প্রোফাইল ও নোটিফিকেশন ম্যানেজ করো।" },
};

export default function Home({ language, onLanguageChange }: { language: Language; onLanguageChange: (value: Language) => void }) {
  const [location] = useLocation();
  const surfaceByPath: Record<string, LearningSurface> = { "/": "home", "/practice": "practice", "/exams": "exams", "/tutor": "tutor", "/progress": "progress", "/study-plan": "studyPlan", "/mistakes": "mistakes", "/bookmarks": "bookmarks", "/settings": "settings" };
  return <PlatformShell language={language} onLanguageChange={onLanguageChange}><LearningReadiness language={language} surface={surfaceByPath[location] ?? "home"} /></PlatformShell>;
}

function LearningReadiness({ language, surface }: { language: Language; surface: LearningSurface }) {
  const [, navigate] = useLocation();
  const { user, isAuthenticated, loading } = useAuth();
  const availability = trpc.learning.publishedContentAvailability.useQuery();
  const progress = trpc.learning.studentProgressSummary.useQuery(undefined, { enabled: isAuthenticated && !loading });
  const copy = learningSurfaceCopy[surface];
  const title = language === "bn" ? copy.bn : copy.en;
  const detail = language === "bn" ? copy.detailBn : copy.detailEn;
  if (loading) return <div className="min-h-[520px] animate-pulse rounded-[28px] bg-white" />;
  const publishedCount = availability.data?.publishedQuestionCount ?? 0;
  const hasPractice = publishedCount > 0;
  const realProgress = progress.data;
  return <div className="card-container mx-auto w-full max-w-5xl space-y-6">
    <section className="relative min-w-0 overflow-hidden rounded-[28px] bg-[#071d33] p-6 text-white shadow-xl shadow-[#071d33]/10 sm:p-8"><div className="absolute -right-16 -top-20 size-72 rounded-full bg-[#16b89b]/20 blur-3xl" /><div className="relative grid min-w-0 gap-7 lg:grid-cols-[1fr_230px]"><div className="min-w-0"><span className="grid size-12 place-items-center rounded-2xl bg-[#16b89b] text-[#071d33]"><Sparkles /></span><p className="mt-6 text-xs font-bold uppercase tracking-[.16em] text-[#7ce3d1]">{language === "bn" ? "স্বচ্ছ লার্নিং স্টেট" : "TRUTHFUL LEARNING STATE"}</p><h1 className="mt-2 max-w-2xl font-display text-3xl font-extrabold leading-tight sm:text-4xl">{isAuthenticated ? (language === "bn" ? `${user?.name ?? "শিক্ষার্থী"}, ${title}` : `Welcome, ${user?.name ?? "student"}. ${title}`) : title}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-300">{detail}</p><div className="mt-6 flex flex-wrap gap-3">{isAuthenticated ? <Button onClick={() => navigate(hasPractice ? "/mcq-lab" : "/notices")} className="mcq-action-button h-11 rounded-xl bg-[#16b89b] text-[#071d33] hover:bg-[#24c8aa] sm:w-auto">{hasPractice ? <Play size={16} fill="currentColor" /> : <Bell size={16} />}{hasPractice ? (language === "bn" ? "অনুমোদিত প্র্যাকটিস খোলো" : "Open approved practice") : (language === "bn" ? "অফিসিয়াল নোটিশ দেখো" : "View official notices")}</Button> : <Button onClick={() => startLogin()} className="mcq-action-button h-11 rounded-xl bg-[#16b89b] text-[#071d33] hover:bg-[#24c8aa] sm:w-auto"><LockKeyhole size={16} />{language === "bn" ? "নিরাপদ সাইন-ইন চালিয়ে যাও" : "Continue to secure sign-in"}</Button>}<Button onClick={() => navigate("/mcq-lab")} variant="outline" className="mcq-action-button h-11 border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white sm:w-auto"><BookOpenCheck size={16} />{language === "bn" ? "প্র্যাকটিস অ্যাভেইলেবিলিটি" : "Practice availability"}</Button></div></div><div className="min-w-0 rounded-2xl border border-white/10 bg-white/5 p-5"><p className="flex items-center gap-2 text-xs font-bold text-[#7ce3d1]"><BookOpenCheck size={15} />{language === "bn" ? "প্রকাশিত প্রশ্ন ব্যাংক" : "PUBLISHED QUESTION BANK"}</p><p className="mt-4 text-4xl font-extrabold">{availability.isLoading ? "…" : publishedCount}</p><p className="mt-1 text-xs leading-5 text-slate-300">{language === "bn" ? "সোর্স-লিংকড প্রশ্ন শিক্ষার্থীর প্র্যাকটিসের জন্য প্রস্তুত" : "source-linked questions ready for student practice"}</p></div></div></section>
    {isAuthenticated && <TodaysStudyGuide language={language} />}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={BookOpenCheck} value={availability.isLoading ? "…" : String(publishedCount)} label={language === "bn" ? "প্রকাশিত প্রশ্ন" : "Published questions"} detail={hasPractice ? (language === "bn" ? "প্র্যাকটিস চালু আছে" : "practice is available") : (language === "bn" ? "রিলিজের অপেক্ষায়" : "waiting for release")} tint="bg-[#e9fbf7] text-[#098873]" /><Metric icon={CheckCircle2} value={isAuthenticated && !progress.isLoading ? String(realProgress?.completedAttempts ?? 0) : "—"} label={language === "bn" ? "সম্পন্ন অ্যাটেম্পট" : "Completed attempts"} detail={isAuthenticated ? (language === "bn" ? "জমা দেওয়া অ্যাটেম্পট থেকে" : "from submitted attempts") : (language === "bn" ? "সাইন ইন প্রয়োজন" : "sign in required")} tint="bg-[#eef3ff] text-[#315bb3]" /><Metric icon={BarChart3} value={isAuthenticated && !progress.isLoading && realProgress?.accuracy !== null && realProgress?.accuracy !== undefined ? `${realProgress.accuracy}%` : "—"} label={language === "bn" ? "আসল নির্ভুলতা" : "Real accuracy"} detail={isAuthenticated ? (language === "bn" ? "উত্তর দেওয়া প্রশ্ন থেকে" : "from answered questions") : (language === "bn" ? "সাইন ইন প্রয়োজন" : "sign in required")} tint="bg-[#fff5e4] text-[#b86b09]" /><Metric icon={Trophy} value={isAuthenticated && !progress.isLoading ? String(realProgress?.studyStreakDays ?? 0) : "—"} label={language === "bn" ? "অ্যাক্টিভিটি স্ট্রিক" : "Activity streak"} detail={isAuthenticated ? (language === "bn" ? "আসল অ্যাটেম্পট দিনের ভিত্তিতে" : "from submitted attempts") : (language === "bn" ? "সাইন ইন প্রয়োজন" : "sign in required")} tint="bg-[#fff0eb] text-[#e45f38]" /></section>
    <section className="rounded-[24px] border border-[#bdeadd] bg-[#effcf9] p-5 text-sm leading-6 text-[#165e54]"><ShieldCheck className="mr-2 inline text-[#088a78]" size={17} /><b>{language === "bn" ? "কোনো ডেমো পারফরম্যান্স ডেটা নয়। " : "No demo performance data. "}</b>{language === "bn" ? "স্ট্রিক, নির্ভুলতা, অ্যাটেম্পট ও কনটেন্ট অ্যাভেইলেবিলিটি লাইভ প্রকাশিত কনটেন্ট এবং তোমার সংরক্ষিত অ্যাক্টিভিটি থেকে আসে।" : "Streaks, accuracy, attempts, and content availability come from live published content and your persisted activity."}</section>
  </div>;
}

function Metric({ icon: Icon, value, label, detail, tint }: { icon: typeof BookOpenCheck; value: string; label: string; detail: string; tint: string }) { return <article className="rounded-2xl bg-white p-4 shadow-[0_10px_24px_rgba(15,40,55,.045)] ring-1 ring-slate-100"><span className={`grid size-9 place-items-center rounded-xl ${tint}`}><Icon size={17} /></span><p className="mt-4 text-2xl font-extrabold text-[#071d33]">{value}</p><p className="mt-1 text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-[11px] leading-4 text-slate-400">{detail}</p></article>; }
