import { PlatformShell } from "@/components/PlatformShell";
import type { Language } from "@/components/PlatformShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, Banknote, Check, FileImage, ShieldCheck, TriangleAlert, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function PaymentReconciliationPage({ language, onLanguageChange }: { language: Language; onLanguageChange: (value: Language) => void }) {
  const copy = (en: string, bn: string) => language === "bn" ? bn : en;
  const utils = trpc.useUtils();
  const requests = trpc.subscription.pendingManualPayments.useQuery();
  const [notes, setNotes] = useState<Record<number, string>>({});
  const review = trpc.subscription.reviewManualPayment.useMutation({
    onSuccess: () => { toast.success(copy("Payment decision recorded and learner notified", "পেমেন্ট সিদ্ধান্ত রেকর্ড হয়েছে এবং শিক্ষার্থীকে জানানো হয়েছে")); utils.subscription.pendingManualPayments.invalidate(); },
    onError: error => toast.error(error.message),
  });
  const error = requests.error;
  if (error) return <PlatformShell language={language} onLanguageChange={onLanguageChange}><AccessState copy={copy} forbidden={error.data?.code === "FORBIDDEN" || error.data?.code === "UNAUTHORIZED"} retry={() => requests.refetch()} /></PlatformShell>;

  return <PlatformShell language={language} onLanguageChange={onLanguageChange}><main className="mx-auto max-w-6xl">
    <header className="rounded-[28px] bg-[#071d33] px-6 py-8 text-white sm:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#7ce3d1]">PAYMENT RECONCILIATION</p><h1 className="mt-2 font-display text-3xl font-extrabold">{copy("Verify first. Grant access second.", "আগে যাচাই। তারপর অ্যাক্সেস।")}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">{copy("Review the payment channel, exact amount, transaction reference, and optional screenshot independently. A learner receives Premium only after your explicit decision.", "পেমেন্ট চ্যানেল, সঠিক পরিমাণ, ট্রানজেকশন রেফারেন্স ও ঐচ্ছিক স্ক্রিনশট স্বাধীনভাবে যাচাই করো। তোমার স্পষ্ট সিদ্ধান্তের পরই শিক্ষার্থী প্রিমিয়াম পাবে।")}</p></div><span className="inline-flex w-fit items-center gap-2 rounded-xl bg-white/10 px-3 py-2 text-xs font-bold text-[#b5f5e7]"><ShieldCheck size={15} />{copy("Administrator-only", "শুধু অ্যাডমিন")}</span></div></header>
    <section className="mt-6 rounded-[26px] bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between gap-4 border-b border-slate-100 pb-4"><div><h2 className="font-display text-xl font-extrabold text-[#071d33]">{copy("Pending manual payments", "পেন্ডিং ম্যানুয়াল পেমেন্ট")}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{copy("Every decision is recorded, and the learner is notified in-app.", "প্রতিটি সিদ্ধান্ত রেকর্ড হয় এবং শিক্ষার্থী ইন-অ্যাপ নোটিফিকেশন পায়।")}</p></div><span className="rounded-lg bg-[#effcf9] px-3 py-1.5 text-sm font-extrabold text-[#087b6c]">{requests.data?.length ?? 0}</span></div>
      {requests.isLoading ? <div className="mt-5 space-y-4">{[1, 2].map(item => <div key={item} className="h-48 animate-pulse rounded-2xl bg-slate-100" />)}</div> : requests.data?.length ? <div className="mt-5 space-y-5">{requests.data.map(payment => {
        const payload = payment.payload && typeof payment.payload === "object" && !Array.isArray(payment.payload) ? payment.payload as Record<string, unknown> : {};
        const note = notes[payment.id] ?? "";
        return <article key={payment.id} className="overflow-hidden rounded-2xl border border-slate-200"><div className="grid gap-5 p-5 lg:grid-cols-[1fr_280px]"><div><div className="flex flex-wrap gap-2"><Badge label={payment.gateway === "bkash_manual" ? "BKASH" : "NAGAD"} /><Badge label={`৳${String(payment.amountBDT)}`} muted /><Badge label={(language === "bn" ? payment.planNameBn : payment.planName).toUpperCase()} muted /></div><h3 className="mt-4 text-base font-extrabold text-[#071d33]">{payment.learnerName ?? copy("Student", "শিক্ষার্থী")}</h3><p className="mt-1 text-sm text-slate-500">{payment.learnerEmail ?? copy("No email recorded", "ইমেইল রেকর্ড নেই")}</p><dl className="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-2"><div><dt className="text-xs font-bold text-slate-500">{copy("Sender number", "প্রেরকের নাম্বার")}</dt><dd className="mt-1 font-mono font-bold text-[#071d33]">{String(payload.senderPhone ?? "—")}</dd></div><div><dt className="text-xs font-bold text-slate-500">{copy("Transaction ID", "ট্রানজেকশন আইডি")}</dt><dd className="mt-1 break-all font-mono font-bold text-[#071d33]">{String(payload.transactionReference ?? "—")}</dd></div><div><dt className="text-xs font-bold text-slate-500">{copy("Submitted", "জমা")}</dt><dd className="mt-1 font-semibold text-[#071d33]">{new Date(payment.createdAt).toLocaleString()}</dd></div><div><dt className="text-xs font-bold text-slate-500">{copy("Internal request", "ইন্টারনাল রিকোয়েস্ট")}</dt><dd className="mt-1 break-all font-mono text-xs font-semibold text-[#071d33]">{payment.internalTransactionId}</dd></div></dl><label className="mt-4 block text-xs font-bold text-slate-600">{copy("Reviewer note (stored with the decision)", "রিভিউয়ার নোট (সিদ্ধান্তের সাথে সংরক্ষিত)")}<textarea value={note} onChange={event => setNotes(current => ({ ...current, [payment.id]: event.target.value }))} maxLength={500} className="mt-2 min-h-20 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-[#16b89b]" placeholder={copy("Record the independent verification basis…", "স্বাধীন যাচাইয়ের ভিত্তি লিখুন…")} /></label><div className="mt-4 flex flex-wrap gap-3"><Button disabled={review.isPending} onClick={() => review.mutate({ paymentId: payment.id, approved: true, reviewerNote: note || undefined })} className="rounded-xl bg-[#087b6c]"><Check size={16} />{copy("Approve & activate Premium", "অনুমোদন ও প্রিমিয়াম চালু")}</Button><Button disabled={review.isPending} onClick={() => review.mutate({ paymentId: payment.id, approved: false, reviewerNote: note || undefined })} variant="outline" className="rounded-xl border-[#e7ad40] text-[#9b6400]"><X size={16} />{copy("Reject request", "রিকোয়েস্ট রিজেক্ট")}</Button></div></div>
          <aside className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-2 text-sm font-extrabold text-[#071d33]"><FileImage size={17} className="text-[#087b6c]" />{copy("Payment proof", "পেমেন্ট প্রমাণ")}</div>{payment.proofUrl ? <a href={payment.proofUrl} target="_blank" rel="noreferrer" className="mt-4 block overflow-hidden rounded-xl border border-slate-200 bg-white"><img src={payment.proofUrl} alt={copy("Submitted payment proof", "জমা দেওয়া পেমেন্ট প্রমাণ")} className="h-48 w-full object-cover" /><p className="truncate px-3 py-2 text-xs font-semibold text-slate-600">{payment.proofOriginalFilename} · {Math.ceil(Number(payment.proofByteSize ?? 0) / 1024)} KB</p></a> : <div className="mt-4 grid min-h-48 place-items-center rounded-xl border border-dashed border-slate-300 bg-white p-4 text-center text-xs leading-5 text-slate-500"><FileImage size={22} className="mb-2 text-slate-400" />{copy("No confirmation screenshot was submitted. Verify the transaction reference directly in the payment channel.", "কোনো কনফার্মেশন স্ক্রিনশট জমা হয়নি। পেমেন্ট চ্যানেলে সরাসরি ট্রানজেকশন রেফারেন্স যাচাই করো।")}</div>}</aside></div></article>;
      })}</div> : <EmptyState copy={copy} />}
    </section>
  </main></PlatformShell>;
}

function Badge({ label, muted = false }: { label: string; muted?: boolean }) { return <span className={`rounded-md px-2 py-1 text-[10px] font-bold ${muted ? "bg-slate-100 text-slate-500" : "bg-[#e9fbf7] text-[#087b6c]"}`}>{label}</span>; }
function EmptyState({ copy }: { copy: (en: string, bn: string) => string }) { return <div className="grid min-h-72 place-items-center py-8 text-center"><div><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-[#e9fbf7] text-[#088a78]"><Banknote /></span><h2 className="mt-4 font-display text-lg font-extrabold text-[#071d33]">{copy("No payment requests await reconciliation", "কোনো পেমেন্ট রিকনসিলিয়েশন বাকি নেই")}</h2><p className="mt-2 max-w-sm text-sm leading-6 text-slate-500">{copy("New bKash or Nagad submissions will appear here with their transaction details and optional proof screenshot.", "নতুন bKash বা Nagad সাবমিশন তাদের ট্রানজেকশন ডিটেইল ও ঐচ্ছিক প্রুফ স্ক্রিনশটসহ এখানে আসবে।")}</p></div></div>; }
function AccessState({ copy, forbidden, retry }: { copy: (en: string, bn: string) => string; forbidden: boolean; retry: () => void }) { return <div className="grid min-h-[520px] place-items-center rounded-[28px] bg-white p-8 text-center shadow-sm"><div className="max-w-md"><span className={`mx-auto grid size-14 place-items-center rounded-2xl ${forbidden ? "bg-[#fff5e4] text-[#b86b09]" : "bg-[#eef3ff] text-[#315bb3]"}`}>{forbidden ? <ShieldCheck /> : <TriangleAlert />}</span><h1 className="mt-5 font-display text-2xl font-extrabold text-[#071d33]">{forbidden ? copy("Admin access required", "অ্যাডমিন অ্যাকসেস প্রয়োজন") : copy("Unable to load payment reconciliation", "পেমেন্ট রিকনসিলিয়েশন লোড করা যাচ্ছে না")}</h1>{!forbidden && <Button onClick={retry} className="mt-6 rounded-xl bg-[#071d33]">{copy("Retry loading", "আবার চেষ্টা করো")}</Button>}</div></div>; }
