import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowDown, ArrowRight, BarChart3, BookOpenCheck, BrainCircuit, ChevronRight, GraduationCap, LogIn, ShieldCheck, Sparkles, Target, TimerReset, Waves } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Link } from "wouter";

export default function PublicLandingPage({ language, onLanguageChange }: { language: "bn" | "en"; onLanguageChange: (value: "bn" | "en") => void }) {
  const copy = (en: string, bn: string) => language === "bn" ? bn : en;
  const explore = () => document.getElementById("subjects")?.scrollIntoView({ behavior: "smooth", block: "start" });
  const availability = trpc.learning.publishedContentAvailability.useQuery();
  const subjects = availability.data?.subjects.slice(0, 4) ?? [];
  const features = [
    [BookOpenCheck, copy("Practice that respects your time", "সময়কে সম্মান করে এমন প্র্যাকটিস"), copy("Choose a direction, then work through reviewed, source-linked questions.", "একটি দিক বেছে নাও, তারপর রিভিউ করা সোর্স-লিংকড প্রশ্ন দিয়ে অনুশীলন করো।")],
    [TimerReset, copy("An exam space with structure", "নিয়ম মেনে এক্সাম স্পেস"), copy("Clear timing, marks, saved selections, and result review in one steady flow.", "সময়, মার্কস, সেভ করা উত্তর আর রিভিউ—সবকিছু এক ধারাবাহিক ফ্লোতে।")],
    [BrainCircuit, copy("Explanations with a grounding", "প্রমাণভিত্তিক ব্যাখ্যা"), copy("Ask the Tutor for evidence-aware help when an approved source is available.", "অনুমোদিত সোর্স থাকলে এআই টিউটরের কাছে প্রমাণভিত্তিক সাহায্য চাও।")],
    [BarChart3, copy("Progress that is earned", "অর্জন করা অগ্রগতি"), copy("Your dashboard becomes useful through submitted attempts, not fabricated statistics.", "জমা দেওয়া অ্যাটেম্পট থেকেই তোমার ড্যাশবোর্ড অর্থবহ হয়, কৃত্রিম সংখ্যায় নয়।")],
  ] as const;

  return <div className="min-h-screen overflow-x-hidden bg-[#f5f8f7] text-[#071d33]">
    <header className="sticky top-0 z-30 border-b border-white/60 bg-[#f5f8f7]/80 backdrop-blur-xl">
      <div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
        <button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="flex items-center gap-3 text-left" aria-label={copy("Back to the top", "শুরুতে ফিরে যাও")}>
          <span className="mcq-public-brand-mark grid size-11 place-items-center rounded-2xl text-[#062033]"><GraduationCap size={23} /></span>
          <span><b className="block font-display text-[1.05rem] tracking-tight">MCQ GURU</b><span className="hidden text-[11px] font-semibold tracking-[.08em] text-slate-500 sm:block">LEARN WITH SIGNAL</span></span>
        </button>
        <nav className="hidden items-center gap-7 text-sm font-bold text-slate-600 md:flex" aria-label={copy("Public navigation", "পাবলিক নেভিগেশন")}>
          <button onClick={explore} className="hover:text-[#087b6c]">{copy("Subjects", "বিষয়")}</button><a href="#method" className="hover:text-[#087b6c]">{copy("Method", "পদ্ধতি")}</a><Link href="/about" className="hover:text-[#087b6c]">{copy("About", "পরিচিতি")}</Link>
        </nav>
        <div className="flex items-center gap-2"><div className="hidden rounded-2xl border border-slate-200 bg-white p-1 shadow-sm sm:flex"><button onClick={() => onLanguageChange("bn")} className={`rounded-xl px-3 py-2 text-xs font-extrabold ${language === "bn" ? "bg-[#071d33] text-white" : "text-slate-500"}`}>বাং</button><button onClick={() => onLanguageChange("en")} className={`rounded-xl px-3 py-2 text-xs font-extrabold ${language === "en" ? "bg-[#e9fbf7] text-[#087b6c]" : "text-slate-500"}`}>EN</button></div><Button onClick={() => startLogin()} className="h-11 rounded-2xl bg-[#071d33] px-4 font-bold shadow-[0_12px_28px_rgba(7,29,51,.16)] hover:bg-[#103151]"><span className="hidden sm:inline">{copy("Sign in", "সাইন ইন")}</span><span className="sm:hidden"><LogIn size={18} /></span><ArrowRight size={16} /></Button></div>
      </div>
    </header>

    <main>
      <section className="mcq-public-hero relative overflow-hidden"><div className="mcq-public-hero__grid" aria-hidden="true" /><div className="mcq-public-hero__glow mcq-public-hero__glow--one" aria-hidden="true" /><div className="mcq-public-hero__glow mcq-public-hero__glow--two" aria-hidden="true" />
        <div className="relative mx-auto grid max-w-7xl gap-12 px-4 pb-20 pt-14 sm:px-6 sm:pb-24 sm:pt-20 lg:grid-cols-[1.02fr_.98fr] lg:items-center lg:px-8">
          <div className="max-w-2xl"><p className="inline-flex items-center gap-2 rounded-full border border-[#a9ecdf] bg-white/70 px-3.5 py-2 text-xs font-extrabold tracking-[.08em] text-[#087b6c] shadow-[0_8px_25px_rgba(22,184,155,.1)]"><Waves size={14} />{copy("A clearer signal for HSC & admission", "এইচএসসি ও ভর্তি প্রস্তুতিতে আরও পরিষ্কার দিকনির্দেশনা")}</p>
            <h1 className="mt-6 font-display text-[2.75rem] font-extrabold leading-[1.01] tracking-[-.045em] text-[#071d33] sm:text-6xl lg:text-[4.15rem]">{copy("Turn effort into a learning signal.", "তোমার চেষ্টাকে শেখার স্পষ্ট দিকনির্দেশনায় বদলে দাও।")}</h1>
            <p className="mt-6 max-w-xl text-base leading-7 text-slate-600 sm:text-lg">{copy("MCQ GURU brings reviewed practice, protected exam attempts, and real progress into one calm, focused study rhythm.", "MCQ GURU রিভিউ করা প্র্যাকটিস, সুরক্ষিত এক্সাম অ্যাটেম্পট এবং আসল অগ্রগতিকে একটি শান্ত, ফোকাসড স্টাডি রিদমে নিয়ে আসে।")}</p>
            <div className="mt-9 flex flex-wrap gap-3"><Button onClick={() => startLogin()} className="h-13 rounded-2xl bg-[#16b89b] px-6 font-extrabold text-[#062033] shadow-[0_16px_36px_rgba(22,184,155,.28)] hover:bg-[#32c8ae]"><Sparkles size={18} />{copy("Build my learning record", "আমার লার্নিং রেকর্ড শুরু করো")}</Button><Button onClick={explore} variant="outline" className="h-13 rounded-2xl border-slate-300 bg-white/70 px-5 font-bold text-[#071d33] hover:bg-white"><ArrowDown size={17} />{copy("See released subjects", "প্রকাশিত বিষয় দেখো")}</Button></div>
            <p className="mt-8 flex max-w-xl items-start gap-3 text-xs leading-5 text-slate-500"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-[#088a78]" />{copy("Questions are selected and scored on the server. Your private study record begins only after secure sign-in.", "প্রশ্ন নির্বাচন ও স্কোরিং সার্ভারেই হয়। নিরাপদ সাইন-ইনের পরই তোমার ব্যক্তিগত স্টাডি রেকর্ড শুরু হয়।")}</p>
          </div>
          <div className="mcq-signal-board" aria-label={copy("MCQ GURU learning signal illustration", "MCQ GURU লার্নিং সিগন্যাল ইলাস্ট্রেশন")}><div className="mcq-signal-board__texture" aria-hidden="true" /><span className="mcq-signal-board__orbit mcq-signal-board__orbit--one" aria-hidden="true" /><span className="mcq-signal-board__orbit mcq-signal-board__orbit--two" aria-hidden="true" /><div className="mcq-signal-board__core" aria-hidden="true"><span /><span /><span /></div><div className="mcq-signal-board__tag mcq-signal-board__tag--north"><span className="size-2 rounded-full bg-[#16b89b]" />{copy("REVIEWED", "রিভিউ করা")}</div><div className="mcq-signal-board__tag mcq-signal-board__tag--east"><Target size={15} />{copy("FOCUSED", "ফোকাসড")}</div><div className="mcq-signal-board__tag mcq-signal-board__tag--south"><BarChart3 size={15} />{copy("REAL PROGRESS", "আসল অগ্রগতি")}</div><div className="mcq-signal-board__metric mcq-signal-board__metric--top"><span>{availability.isLoading ? "…" : subjects.length}</span><small>{copy("released subject views", "প্রকাশিত বিষয় প্রিভিউ")}</small></div><div className="mcq-signal-board__metric mcq-signal-board__metric--bottom"><span>01</span><small>{copy("secure start", "নিরাপদ শুরু")}</small></div><div className="mcq-signal-board__caption"><span className="mcq-signal-board__caption-line" aria-hidden="true" /><p>{copy("Find the next useful move — not just the next question.", "শুধু পরের প্রশ্ন নয়, খুঁজে নাও পরের দরকারি পদক্ষেপ।")}</p></div></div>
        </div>
      </section>
      <section id="method" className="relative mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-2xl"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#087b6c]">{copy("THE MCQ GURU RHYTHM", "MCQ GURU রিদম")}</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl">{copy("Prepare with a sequence that makes sense.", "এমন একটি ধারাবাহিকতায় প্রস্তুতি নাও যা সত্যিই কাজ করে।")}</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">{copy("No demo scorecards. No answer-key shortcuts. A reliable study space that gets stronger as effort becomes real data.", "ডেমো স্কোরকার্ড নয়, উত্তর লুকানোর কোনো শর্টকাট নয়—তোমার চেষ্টা যখন আসল ডেটায় বদলাবে, তখন আরও শক্তিশালী হবে স্টাডি স্পেস।")}</p></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon, title, detail], index) => <article key={title} className="mcq-public-feature rounded-[26px] bg-white p-6 shadow-[0_14px_38px_rgba(7,29,51,.06)] ring-1 ring-slate-100"><span className="flex items-center justify-between text-xs font-extrabold text-[#087b6c]"><span>0{index + 1}</span><Icon size={20} /></span><h3 className="mt-9 text-lg font-extrabold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{detail}</p><span className="mt-6 inline-flex items-center gap-1 text-xs font-bold text-[#087b6c]">{copy("Keep moving", "এগিয়ে চলো")}<ChevronRight size={14} /></span></article>)}</div></section>
      <section id="subjects" className="border-y border-[#dce9e6] bg-[#ecf5f3]"><div className="mx-auto grid max-w-7xl gap-9 px-4 py-16 sm:px-6 lg:grid-cols-[.78fr_1.22fr] lg:items-center lg:px-8"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#087b6c]">{copy("LIVE CAPACITY SIGNAL", "লাইভ ক্যাপাসিটি সিগন্যাল")}</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-tight">{copy("Start from what is truly ready.", "যা সত্যিই প্রস্তুত, সেখান থেকেই শুরু করো।")}</h2><p className="mt-5 text-sm leading-6 text-slate-600">{copy("Subject availability comes from the active source-linked question bank. We show only reviewed content that is ready for protected practice.", "বিষয়ের অ্যাভেইলেবিলিটি আসে অ্যাকটিভ সোর্স-লিংকড প্রশ্ন ব্যাংক থেকে। সুরক্ষিত প্র্যাকটিসের জন্য প্রস্তুত রিভিউ করা কনটেন্টই শুধু দেখানো হয়।")}</p><Button onClick={() => startLogin("/practice")} className="mt-7 h-12 rounded-2xl bg-[#071d33] px-5 font-bold hover:bg-[#103151]"><BookOpenCheck size={17} />{copy("Explore after sign-in", "সাইন ইন করে এক্সপ্লোর করো")}</Button></div><div className="grid gap-3 sm:grid-cols-2">{availability.isLoading ? [1, 2, 3, 4].map(item => <div key={item} className="h-40 animate-pulse rounded-[22px] bg-white/75" />) : subjects.map((subject, index) => <article key={subject.subjectId} className="rounded-[22px] border border-white bg-white/85 p-5 shadow-[0_14px_30px_rgba(7,29,51,.05)]"><div className="flex items-start justify-between"><span className="grid size-9 place-items-center rounded-xl bg-[#071d33] text-xs font-extrabold text-[#7ce3d1]">{String(index + 1).padStart(2, "0")}</span><span className="text-xs font-bold text-[#087b6c]">{subject.questionCount}</span></div><p className="mt-7 text-base font-extrabold">{language === "bn" ? subject.nameBn : subject.nameEn}</p><p className="mt-1 text-xs leading-5 text-slate-500">{copy("reviewed source-linked questions", "রিভিউ করা সোর্স-লিংকড প্রশ্ন")}</p></article>)}{!availability.isLoading && !subjects.length && <div className="rounded-[22px] border border-[#f2d8b3] bg-[#fffaf0] p-5 text-sm leading-6 text-[#784512]">{copy("No reviewed subject capacity is published yet.", "এখনো কোনো রিভিউ করা বিষয়ভিত্তিক কনটেন্ট প্রকাশিত হয়নি।")}</div>}</div></div></section>
      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="mcq-public-close relative overflow-hidden rounded-[32px] px-6 py-12 text-white sm:px-12"><div className="mcq-public-close__line" aria-hidden="true" /><div className="relative max-w-2xl"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#7ce3d1]">{copy("YOUR NEXT SIGNAL", "তোমার পরের সিগন্যাল")}</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-tight sm:text-4xl">{copy("A better study record starts with one honest attempt.", "একটি সৎ অ্যাটেম্পট থেকেই শুরু হয় আরও ভালো স্টাডি রেকর্ড।")}</h2><p className="mt-4 max-w-xl text-sm leading-6 text-slate-300">{copy("Sign in, set your focus, and let MCQ GURU turn reviewed practice into a record you can trust.", "সাইন ইন করো, তোমার ফোকাস ঠিক করো এবং MCQ GURU-কে রিভিউ করা প্র্যাকটিসকে নির্ভরযোগ্য রেকর্ডে বদলাতে দাও।")}</p><Button onClick={() => startLogin()} className="mt-8 h-12 rounded-2xl bg-[#16b89b] px-6 font-extrabold text-[#062033] hover:bg-[#32c8ae]"><Sparkles size={17} />{copy("Begin my record", "আমার রেকর্ড শুরু করো")}</Button></div></div></section>
    </main>
    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><p>© {new Date().getFullYear()} MCQ GURU</p><nav className="flex flex-wrap gap-x-5 gap-y-2" aria-label={copy("Public information", "পাবলিক তথ্য")}><Link href="/about" className="hover:text-[#087b6c]">{copy("About", "পরিচিতি")}</Link><Link href="/privacy" className="hover:text-[#087b6c]">{copy("Privacy", "গোপনীয়তা")}</Link><Link href="/terms" className="hover:text-[#087b6c]">{copy("Terms", "ব্যবহারের শর্ত")}</Link><Link href="/contact" className="hover:text-[#087b6c]">{copy("Contact", "যোগাযোগ")}</Link></nav></div></footer>
  </div>;
}
