import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowRight, BarChart3, BookOpenCheck, Brain, CheckCircle2, FileText, GraduationCap, Menu, ShieldCheck, Sparkles, Target } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Link } from "wouter";

export default function PublicLandingPage({ language, onLanguageChange }: { language: "bn" | "en"; onLanguageChange: (value: "bn" | "en") => void }) {
  const copy = (en: string, bn: string) => language === "bn" ? bn : en;
  const explore = () => document.getElementById("subjects")?.scrollIntoView({ behavior: "smooth", block: "start" });
  const features = [
    [BookOpenCheck, copy("MCQ practice", "এমসিকিউ প্র্যাকটিস"), copy("Work through reviewed, source-linked questions when they are published.", "রিভিউ করা, সোর্স-লিংকড প্রশ্ন প্রকাশিত হলে সেগুলো দিয়ে প্র্যাকটিস করো।")],
    [FileText, copy("Mock exams", "মক এক্সাম"), copy("Take timed attempts with transparent marking rules and saved results.", "স্বচ্ছ মার্কিং রুল ও সংরক্ষিত ফলাফলের সাথে টাইমড অ্যাটেম্পট দাও।")],
    [Brain, copy("AI Tutor", "এআই টিউটর"), copy("Ask for explanations grounded in approved evidence when available.", "প্রমাণ থাকলে অনুমোদিত এভিডেন্সের ভিত্তিতে ব্যাখ্যা চাও।")],
    [BarChart3, copy("Progress tracking", "অগ্রগতি ট্র্যাকিং"), copy("Build a real record from your submitted attempts, not demo statistics.", "ডেমো স্ট্যাটিসটিক্স নয়, জমা দেওয়া অ্যাটেম্পট থেকে আসল রেকর্ড তৈরি করো।")],
  ] as const;
  const availability = trpc.learning.publishedContentAvailability.useQuery();
  const subjects = availability.data?.subjects.slice(0, 5) ?? [];
  return <div className="min-h-screen overflow-x-hidden bg-[#f4f7f7] text-[#071d33]">
    <header className="sticky top-0 z-30 border-b border-slate-200/80 bg-[#f4f7f7]/90 backdrop-blur"><div className="mx-auto flex h-[72px] max-w-6xl items-center justify-between px-4 sm:px-6"><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="flex items-center gap-3 text-left"><span className="grid size-10 place-items-center rounded-2xl bg-[#16b89b] shadow-[0_8px_24px_rgba(22,184,155,.25)]"><GraduationCap size={22} /></span><span><b className="block font-display text-lg tracking-tight">MCQ GURU</b><span className="hidden text-xs text-slate-500 sm:block">Learn. Practice. Rise.</span></span></button><div className="flex items-center gap-2"><div className="rounded-xl bg-white p-1 shadow-sm ring-1 ring-slate-200"><button onClick={() => onLanguageChange("bn")} className={`rounded-lg px-2.5 py-1.5 text-xs font-bold ${language === "bn" ? "bg-[#071d33] text-white" : "text-slate-500"}`}>বাং</button><button onClick={() => onLanguageChange("en")} className={`rounded-lg px-2.5 py-1.5 text-xs font-bold ${language === "en" ? "bg-[#071d33] text-white" : "text-slate-500"}`}>EN</button></div><Button onClick={() => startLogin()} className="h-10 rounded-xl bg-[#071d33] px-4 text-sm">{copy("Sign in", "সাইন ইন")}<ArrowRight size={15} /></Button></div></div></header>
    <main>
      <section className="relative overflow-hidden"><div className="absolute inset-x-0 top-0 h-[480px] bg-[radial-gradient(circle_at_78%_18%,rgba(22,184,155,.22),transparent_32%),radial-gradient(circle_at_15%_32%,rgba(64,132,255,.12),transparent_28%)]" /><div className="relative mx-auto grid max-w-6xl gap-10 px-4 pb-16 pt-14 sm:px-6 sm:pb-24 sm:pt-20 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="inline-flex items-center gap-2 rounded-full border border-[#bdeadd] bg-[#effcf9] px-3 py-1.5 text-xs font-bold text-[#087b6c]"><Sparkles size={14} />{copy("For HSC & admission preparation", "এইচএসসি ও ভর্তি প্রস্তুতির জন্য")}</p><h1 className="mt-5 max-w-2xl font-display text-4xl font-extrabold leading-[1.06] tracking-tight sm:text-5xl">{copy("HSC preparation, made smarter.", "আরও স্মার্টভাবে এইচএসসি প্রস্তুতি নাও।")}</h1><p className="mt-5 max-w-xl text-base leading-7 text-slate-600">{copy("Practice MCQs, prepare for exams, learn from explanations, and track real progress as you build confidence for your next exam.", "এমসিকিউ প্র্যাকটিস করো, এক্সামের প্রস্তুতি নাও, ব্যাখ্যা থেকে শেখো এবং নিজের আসল অগ্রগতি ট্র্যাক করে আত্মবিশ্বাস গড়ে তোলো।")}</p><div className="mt-8 flex flex-wrap gap-3"><Button onClick={() => startLogin()} className="h-12 rounded-xl bg-[#16b89b] px-5 font-bold text-[#062033] hover:bg-[#24c8aa]"><BookOpenCheck size={17} />{copy("Start practicing", "প্র্যাকটিস শুরু করো")}</Button><Button onClick={explore} variant="outline" className="h-12 rounded-xl border-slate-300 px-5"><Target size={17} />{copy("Explore subjects", "বিষয়গুলো দেখো")}</Button></div><p className="mt-5 flex items-center gap-2 text-xs leading-5 text-slate-500"><ShieldCheck size={15} className="shrink-0 text-[#088a78]" />{copy("Your personal records begin only after secure sign-in and real learning activity.", "নিরাপদ সাইন-ইন এবং আসল লার্নিং অ্যাক্টিভিটির পরই তোমার ব্যক্তিগত রেকর্ড শুরু হয়।")}</p></div><div className="rounded-[30px] border border-white/70 bg-white/80 p-5 shadow-[0_24px_70px_rgba(7,29,51,.12)] backdrop-blur sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#088a78]">{copy("A focused learning space", "ফোকাসড লার্নিং স্পেস")}</p><div className="mt-5 space-y-3">{[["01", copy("Practice with purpose", "লক্ষ্য নিয়ে প্র্যাকটিস")], ["02", copy("Understand every answer", "প্রতিটি উত্তর বুঝে নাও")], ["03", copy("Improve from real attempts", "আসল অ্যাটেম্পট থেকে উন্নতি করো")]].map(([number, label]) => <div key={number} className="flex items-center gap-4 rounded-2xl bg-[#f8fbfb] p-4"><span className="grid size-9 place-items-center rounded-xl bg-[#071d33] text-xs font-bold text-[#7ce3d1]">{number}</span><span className="text-sm font-bold text-[#071d33]">{label}</span><CheckCircle2 className="ml-auto text-[#16b89b]" size={18} /></div>)}</div></div></div></section>
      <section className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#088a78]">{copy("HOW MCQ GURU HELPS", "MCQ GURU কীভাবে সাহায্য করে")}</p><h2 className="mt-2 font-display text-3xl font-extrabold">{copy("Everything you need to learn with direction.", "দিকনির্দেশনা নিয়ে শেখার জন্য প্রয়োজনীয় সবকিছু।")}</h2></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon, title, detail]) => <article key={title} className="rounded-2xl bg-white p-5 shadow-[0_12px_30px_rgba(15,40,55,.06)] ring-1 ring-slate-100"><span className="grid size-10 place-items-center rounded-xl bg-[#e9fbf7] text-[#088a78]"><Icon size={19} /></span><h3 className="mt-4 text-sm font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{detail}</p></article>)}</div></section>
      <section id="subjects" className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-6xl gap-8 px-4 py-14 sm:px-6 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#088a78]">{copy("SUBJECT PREVIEW", "বিষয়ের প্রিভিউ")}</p><h2 className="mt-2 font-display text-3xl font-extrabold">{copy("Prepare from released HSC subjects.", "প্রকাশিত এইচএসসি বিষয় থেকে প্রস্তুতি নাও।")}</h2><p className="mt-4 text-sm leading-6 text-slate-500">{copy("Subject availability is read from the active source-linked question bank. Nothing is presented as a ready learning path before questions have been reviewed and published.", "বিষয়ের অ্যাভেইলেবিলিটি অ্যাকটিভ সোর্স-লিংকড প্রশ্ন ব্যাংক থেকে নেওয়া হয়। প্রশ্ন রিভিউ ও প্রকাশের আগে কোনো কিছু রেডি লার্নিং পাথ হিসেবে দেখানো হয় না।")}</p></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{availability.isLoading ? [1, 2, 3, 4].map(item => <div key={item} className="h-40 animate-pulse rounded-2xl bg-slate-100" />) : subjects.map((subject, index) => <article key={subject.subjectId} className="rounded-2xl border border-slate-200 bg-[#f8fbfb] p-4"><span className="text-xs font-bold text-[#088a78]">{String(index + 1).padStart(2, "0")}</span><p className="mt-4 text-base font-extrabold">{language === "bn" ? subject.nameBn : subject.nameEn}</p><p className="mt-1 text-xs leading-5 text-slate-500">{copy(`${subject.questionCount} reviewed, source-linked questions currently published.`, `বর্তমানে ${subject.questionCount}টি রিভিউ করা, সোর্স-লিংকড প্রশ্ন প্রকাশিত আছে।`)}</p><Button onClick={() => startLogin("/practice")} variant="outline" className="mt-4 min-h-10 w-full rounded-xl text-xs"><ArrowRight size={14} />{copy("Explore after sign-in", "সাইন ইন করে দেখো")}</Button></article>)}{!availability.isLoading && !subjects.length && <div className="rounded-2xl border border-[#f2d8b3] bg-[#fffaf0] p-5 text-sm leading-6 text-[#784512]">{copy("No reviewed subject capacity is published yet.", "এখনো কোনো রিভিউ করা বিষয়ভিত্তিক কনটেন্ট প্রকাশিত হয়নি।")}</div>}</div></div></section>
      <section className="mx-auto max-w-6xl px-4 py-14 text-center sm:px-6"><div className="rounded-[28px] bg-[#071d33] px-6 py-10 text-white sm:px-10"><h2 className="font-display text-3xl font-extrabold">{copy("Ready to start with a plan that is yours?", "তোমার নিজের প্ল্যান দিয়ে শুরু করতে প্রস্তুত?")}</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-slate-300">{copy("Sign in securely, complete a short study profile, and begin building your real MCQ GURU learning record.", "নিরাপদভাবে সাইন ইন করো, ছোট স্টাডি প্রোফাইল সম্পন্ন করো এবং নিজের আসল MCQ GURU লার্নিং রেকর্ড তৈরি করা শুরু করো।")}</p><Button onClick={() => startLogin()} className="mt-7 h-12 rounded-xl bg-[#16b89b] px-6 font-bold text-[#062033] hover:bg-[#24c8aa]"><ArrowRight size={17} />{copy("Get started", "শুরু করো")}</Button></div></section>
    </main><footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-7 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between sm:px-6"><p>© {new Date().getFullYear()} MCQ GURU</p><nav className="flex flex-wrap gap-x-5 gap-y-2" aria-label="Public information"><Link href="/about" className="hover:text-[#087b6c]">{copy("About", "পরিচিতি")}</Link><Link href="/privacy" className="hover:text-[#087b6c]">{copy("Privacy", "গোপনীয়তা")}</Link><Link href="/terms" className="hover:text-[#087b6c]">{copy("Terms", "ব্যবহারের শর্ত")}</Link><Link href="/contact" className="hover:text-[#087b6c]">{copy("Contact", "যোগাযোগ")}</Link></nav></div></footer>
  </div>;
}
