import { PlatformShell } from "@/components/PlatformShell";
import type { Language } from "@/components/PlatformShell";
import { Button } from "@/components/ui/button";
import { useSubscription } from "@/hooks/useSubscription";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, Check, CheckCircle2, Clipboard, Crown, ImagePlus, LockKeyhole, ShieldCheck, X } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const freeFeatures = ["20 practice questions daily", "1 full exam weekly", "5 Tutor questions daily", "2 Image Solver requests weekly", "Basic progress and profile"];
const supportedProofTypes = ["image/jpeg", "image/png", "image/webp"] as const;
type PaymentProof = { originalFilename: string; contentType: typeof supportedProofTypes[number]; dataUrl: string };

export default function UpgradePage({ language, onLanguageChange }: { language: Language; onLanguageChange: (value: Language) => void }) {
  const copy = (en: string, bn: string) => language === "bn" ? bn : en;
  const { subscription } = useSubscription();
  const plans = trpc.subscription.plans.useQuery();
  const [selectedPlanId, setSelectedPlanId] = useState<number | null>(null);
  const [method, setMethod] = useState<"bkash_manual" | "nagad_manual">("bkash_manual");
  const [senderPhone, setSenderPhone] = useState("");
  const [transactionReference, setTransactionReference] = useState("");
  const [proof, setProof] = useState<PaymentProof | null>(null);
  const selectedPlan = plans.data?.find(plan => plan.id === selectedPlanId);
  const receiverNumber = "01956953111";
  const manualRequest = trpc.subscription.requestManualPayment.useMutation({
    onSuccess: result => {
      toast.success(result.proofUploaded ? copy("Payment request and confirmation screenshot submitted", "পেমেন্ট রিকোয়েস্ট ও কনফার্মেশন স্ক্রিনশট জমা হয়েছে") : copy("Payment request submitted for verification", "পেমেন্ট রিকোয়েস্ট ভেরিফিকেশনের জন্য জমা হয়েছে"));
      setTransactionReference(""); setProof(null);
    },
    onError: error => toast.error(error.message),
  });

  useEffect(() => { if (!selectedPlanId && plans.data?.[0]) setSelectedPlanId(plans.data[0].id); }, [plans.data, selectedPlanId]);

  const copyReceiver = async () => { await navigator.clipboard.writeText(receiverNumber); toast.success(copy("Number copied", "নাম্বার কপি হয়েছে")); };
  const selectProof = (file?: File) => {
    if (!file) return;
    if (!supportedProofTypes.includes(file.type as PaymentProof["contentType"])) { toast.error(copy("Use a JPEG, PNG, or WebP image", "JPEG, PNG বা WebP ছবি ব্যবহার করো")); return; }
    if (file.size > 5 * 1024 * 1024) { toast.error(copy("Screenshot must be 5 MB or smaller", "স্ক্রিনশট ৫ MB বা ছোট হতে হবে")); return; }
    const reader = new FileReader();
    reader.onload = () => setProof({ originalFilename: file.name, contentType: file.type as PaymentProof["contentType"], dataUrl: String(reader.result) });
    reader.onerror = () => toast.error(copy("Unable to read this screenshot", "এই স্ক্রিনশট পড়া যাচ্ছে না"));
    reader.readAsDataURL(file);
  };

  return <PlatformShell language={language} onLanguageChange={onLanguageChange}><main className="mx-auto max-w-6xl">
    <section className="overflow-hidden rounded-[30px] bg-[#071d33] px-6 py-10 text-white sm:px-10"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#7ce3d1]">MCQ GURU PREMIUM</p><h1 className="mt-3 max-w-2xl font-display text-3xl font-extrabold leading-tight sm:text-4xl">{copy("Unlock your full learning potential.", "তোমার সম্পূর্ণ লার্নিং সক্ষমতা আনলক করো।")}</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-300">{copy("Keep your source-governed practice, full exam access, tutor support, revision tools, and detailed learning insights together.", "সোর্স-গভর্নড প্র্যাকটিস, পূর্ণ এক্সাম অ্যাক্সেস, টিউটর সাপোর্ট, রিভিশন টুল ও বিস্তারিত ইনসাইট একসাথে রাখো।")}</p></section>
    <section className="mt-6 grid gap-5 lg:grid-cols-3"><article className="rounded-[26px] bg-white p-6 shadow-sm ring-1 ring-slate-100"><LockKeyhole className="text-slate-500" /><h2 className="mt-4 font-display text-xl font-extrabold text-[#071d33]">{copy("Free", "ফ্রি")}</h2><p className="mt-2 text-3xl font-extrabold text-[#071d33]">৳০<span className="text-sm font-medium text-slate-500">/{copy("month", "মাস")}</span></p><p className="mt-3 text-sm text-slate-500">{copy("A useful forever plan after the free trial.", "ফ্রি ট্রায়ালের পরও ব্যবহারযোগ্য প্ল্যান।")}</p><ul className="mt-5 space-y-3 text-sm text-slate-600">{freeFeatures.map(feature => <li key={feature} className="flex gap-2"><Check size={16} className="mt-0.5 shrink-0 text-[#088a78]" />{feature}</li>)}</ul><div className="mt-6 rounded-xl bg-slate-100 px-3 py-2 text-center text-xs font-bold text-slate-500">{subscription?.isFree ? copy("Current plan", "বর্তমান প্ল্যান") : copy("Available anytime", "সবসময় পাওয়া যাবে")}</div></article>
      {plans.isLoading ? [1, 2].map(key => <div key={key} className="h-[420px] animate-pulse rounded-[26px] bg-slate-100" />) : plans.data?.map(plan => <article key={plan.id} className={`relative rounded-[26px] border-2 bg-white p-6 shadow-[0_18px_42px_rgba(22,184,155,.15)] ${selectedPlanId === plan.id ? "border-[#071d33]" : "border-[#16b89b]"}`}><span className="absolute right-5 top-5 rounded-full bg-[#e9fbf7] px-3 py-1 text-[10px] font-extrabold uppercase tracking-[.12em] text-[#087b6c]">{plan.durationDays === 365 ? copy("Best value", "সেরা ভ্যালু") : copy("Most flexible", "সবচেয়ে ফ্লেক্সিবল")}</span><Crown className="text-[#088a78]" /><h2 className="mt-4 font-display text-xl font-extrabold text-[#071d33]">{language === "bn" ? plan.nameBn : plan.name}</h2><p className="mt-2 text-3xl font-extrabold text-[#071d33]">৳{String(plan.priceBDT)}<span className="text-sm font-medium text-slate-500">/{plan.durationDays === 365 ? copy("year", "বছর") : copy("month", "মাস")}</span></p><p className="mt-3 min-h-10 text-sm leading-5 text-slate-500">{language === "bn" ? plan.descriptionBn : plan.description}</p><ul className="mt-5 space-y-3 text-sm text-slate-600">{plan.features.slice(0, 5).map(feature => <li key={feature} className="flex gap-2"><BadgeCheck size={16} className="mt-0.5 shrink-0 text-[#088a78]" />{feature.replaceAll("_", " ")}</li>)}</ul><button type="button" onClick={() => setSelectedPlanId(plan.id)} className={`mt-6 w-full rounded-xl py-3 text-xs font-bold transition ${selectedPlanId === plan.id ? "bg-[#071d33] text-white" : "border border-slate-200 text-slate-600 hover:border-[#071d33]"}`}>{selectedPlanId === plan.id ? copy("Selected for bKash/Nagad", "bKash/Nagad-এর জন্য নির্বাচিত") : copy("Pay with bKash or Nagad", "bKash বা Nagad-এ পেমেন্ট")}</button></article>)}</section>
    {selectedPlan && <section className="mt-7 overflow-hidden rounded-[26px] border border-slate-200 bg-white shadow-sm"><div className="bg-[#fff8e7] px-6 py-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#9b6400]">{copy("Manual payment verification", "ম্যানুয়াল পেমেন্ট ভেরিফিকেশন")}</p><h2 className="mt-1 font-display text-xl font-extrabold text-[#071d33]">{copy(`Pay ৳${String(selectedPlan.priceBDT)} for ${language === "bn" ? selectedPlan.nameBn : selectedPlan.name}`, `${language === "bn" ? selectedPlan.nameBn : selectedPlan.name}-এর জন্য ৳${String(selectedPlan.priceBDT)} পেমেন্ট করো`)}</h2></div><div className="grid gap-6 p-6 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-sm leading-6 text-slate-600">{copy("Send the exact plan amount to the displayed personal payment number using bKash or Nagad. Then submit the sender number, transaction ID, and optional confirmation screenshot. A reviewer must verify the payment before Premium access is activated.", "bKash বা Nagad ব্যবহার করে দেখানো ব্যক্তিগত পেমেন্ট নাম্বারে ঠিক প্ল্যানের পরিমাণ পাঠাও। তারপর প্রেরকের নাম্বার, ট্রানজেকশন আইডি ও চাইলে কনফার্মেশন স্ক্রিনশট জমা দাও। রিভিউয়ার পেমেন্ট যাচাই না করা পর্যন্ত প্রিমিয়াম অ্যাক্সেস চালু হবে না।")}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => setMethod("bkash_manual")} className={`rounded-2xl border p-4 text-left ${method === "bkash_manual" ? "border-[#e2136e] bg-[#fff3f8]" : "border-slate-200"}`}><img src="/manus-storage/bkash-logo-cropped_cdc1fee0.png" alt="bKash" className="h-10 w-auto object-contain" /><p className="mt-3 text-sm font-extrabold text-[#071d33]">bKash</p></button><button type="button" onClick={() => setMethod("nagad_manual")} className={`rounded-2xl border p-4 text-left ${method === "nagad_manual" ? "border-[#ef5b22] bg-[#fff6ef]" : "border-slate-200"}`}><img src="/manus-storage/nagad-logo-cropped_b2e65c13.png" alt="Nagad" className="h-10 w-auto object-contain" /><p className="mt-3 text-sm font-extrabold text-[#071d33]">Nagad</p></button></div><div className="mt-4 flex items-center justify-between rounded-2xl bg-[#071d33] p-4 text-white"><div><p className="text-xs text-slate-300">{copy("Receiver number", "রিসিভার নাম্বার")}</p><p className="mt-1 font-mono text-xl font-extrabold tracking-wider">{receiverNumber}</p></div><button type="button" onClick={copyReceiver} className="rounded-xl bg-white/10 p-3 text-[#7ce3d1]" aria-label={copy("Copy receiver number", "রিসিভার নাম্বার কপি করো")}><Clipboard size={18} /></button></div></div>
      <form onSubmit={event => { event.preventDefault(); manualRequest.mutate({ planId: selectedPlan.id, method, senderPhone, transactionReference, proof: proof ?? undefined }); }} className="rounded-2xl border border-slate-200 p-5"><p className="flex items-center gap-2 text-sm font-bold text-[#071d33]"><CheckCircle2 size={17} className="text-[#088a78]" />{copy("Submit for verification", "ভেরিফিকেশনের জন্য জমা দাও")}</p><label className="mt-5 block text-xs font-bold text-slate-600">{copy("Your bKash/Nagad number", "তোমার bKash/Nagad নাম্বার")}<input value={senderPhone} onChange={event => setSenderPhone(event.target.value)} inputMode="numeric" pattern="01[0-9]{9}" required className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-[#16b89b]" placeholder="01XXXXXXXXX" /></label><label className="mt-4 block text-xs font-bold text-slate-600">{copy("Transaction ID", "ট্রানজেকশন আইডি")}<input value={transactionReference} onChange={event => setTransactionReference(event.target.value)} required minLength={4} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-[#16b89b]" placeholder={copy("Example: 8N7Q2ABCD", "উদাহরণ: 8N7Q2ABCD")} /></label><label className="mt-4 block"><span className="text-xs font-bold text-slate-600">{copy("Payment confirmation screenshot (optional)", "পেমেন্ট কনফার্মেশন স্ক্রিনশট (ঐচ্ছিক)")}</span><span className="mt-2 flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-3 text-xs text-slate-500 hover:border-[#16b89b]"><ImagePlus size={18} className="text-[#088a78]" /><span>{proof ? proof.originalFilename : copy("JPEG, PNG, or WebP — up to 5 MB", "JPEG, PNG বা WebP — সর্বোচ্চ ৫ MB")}</span><input type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={event => selectProof(event.target.files?.[0])} /></span></label>{proof && <div className="relative mt-3 overflow-hidden rounded-xl border border-slate-200"><img src={proof.dataUrl} alt={copy("Selected payment confirmation", "নির্বাচিত পেমেন্ট কনফার্মেশন")} className="h-28 w-full object-cover" /><button type="button" onClick={() => setProof(null)} className="absolute right-2 top-2 rounded-full bg-black/60 p-1.5 text-white" aria-label={copy("Remove screenshot", "স্ক্রিনশট সরাও")}><X size={14} /></button></div>}<Button type="submit" disabled={manualRequest.isPending} className="mt-5 h-11 w-full rounded-xl bg-[#071d33]">{manualRequest.isPending ? copy("Submitting…", "জমা হচ্ছে…") : copy("Submit payment request", "পেমেন্ট রিকোয়েস্ট জমা দাও")}</Button><p className="mt-3 text-[11px] leading-5 text-slate-500">{copy("Do not submit sensitive PINs, OTPs, or account passwords. A request and screenshot are not payment confirmation.", "PIN, OTP বা অ্যাকাউন্ট পাসওয়ার্ড কখনও জমা দিও না। রিকোয়েস্ট ও স্ক্রিনশট পেমেন্ট নিশ্চিতকরণ নয়।")}</p></form></div></section>}
    <section className="mt-7 rounded-[26px] bg-white p-6 shadow-sm ring-1 ring-slate-100"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-[#088a78]" /><div><h2 className="font-display text-lg font-extrabold text-[#071d33]">{copy("Payment and cancellation", "পেমেন্ট ও ক্যান্সেলেশন")}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{copy("Manual bKash/Nagad requests are reviewed before access changes. You can turn off auto-renewal in your profile; paid access remains active until its recorded end date.", "অ্যাক্সেস পরিবর্তনের আগে ম্যানুয়াল bKash/Nagad রিকোয়েস্ট রিভিউ করা হয়। প্রোফাইল থেকে অটো-রিনিউ বন্ধ করা যায়; পেইড অ্যাক্সেস রেকর্ড করা শেষ তারিখ পর্যন্ত চালু থাকে।")}</p></div></div></section>
  </main></PlatformShell>;
}
