import { Button } from "@/components/ui/button";
import { Trophy } from "lucide-react";
import type { Language } from "./PlatformShell";

type AdmissionBenchmark = { patternId: number; institution: string | null; title: string; unit: string | null; session: string | null; sourceUrl: string | null; cutMark: number; officialMaxMarks: number; latestAttempt: { id: number; score: number; maxMarks: number; submittedAt: Date | string | null } | null; gap: number | null; state: "comparable" | "no_compatible_mock" };

export function AdmissionScoreBenchmark({ language, signedIn, loading, items, onOpenAdmission }: { language: Language; signedIn: boolean; loading: boolean; items: AdmissionBenchmark[] | undefined; onOpenAdmission: () => void }) {
  const copy = (en: string, bn: string) => language === "bn" ? bn : en;
  if (!signedIn) return <section className="rounded-[24px] border border-[#e7ddfb] bg-[#fbf9ff] p-5 sm:p-6"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#6d4ab7] text-white"><Trophy size={19} /></span><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#6d4ab7]">{copy("ADMISSION SCORE BENCHMARK", "ভর্তি স্কোর বেঞ্চমার্ক")}</p><h2 className="mt-1 font-display text-xl font-extrabold text-[#071d33]">{copy("Sign in to compare a saved mock score", "সেভ করা মক স্কোর তুলনা করতে সাইন ইন করো")}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{copy("Benchmarks use your persisted results and source-reviewed historical cut marks only.", "বেঞ্চমার্ক শুধু তোমার সংরক্ষিত ফলাফল এবং সোর্স-রিভিউড ঐতিহাসিক কাট মার্ক ব্যবহার করে।")}</p></div></div></section>;
  if (loading) return <section className="rounded-[24px] bg-white p-5 shadow-sm sm:p-6" aria-busy="true"><div className="h-4 w-48 animate-pulse rounded bg-slate-100" /><div className="mt-4 h-28 animate-pulse rounded-2xl bg-slate-100" /></section>;
  const comparable = items?.find(item => item.state === "comparable");
  const reviewed = items?.[0];
  if (!reviewed) return <section className="rounded-[24px] border border-[#e7ddfb] bg-[#fbf9ff] p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#6d4ab7] text-white"><Trophy size={19} /></span><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#6d4ab7]">{copy("ADMISSION SCORE BENCHMARK", "ভর্তি স্কোর বেঞ্চমার্ক")}</p><h2 className="mt-1 font-display text-xl font-extrabold text-[#071d33]">{copy("No reviewed prior-year cut mark is available", "কোনো রিভিউড আগের বছরের কাট মার্ক পাওয়া যাচ্ছে না")}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{copy("A comparison appears when an administrator activates a source-linked historical cut mark and matching official score scale.", "অ্যাডমিন সোর্স-লিংকড ঐতিহাসিক কাট মার্ক ও মিল থাকা অফিসিয়াল স্কোর স্কেল অ্যাক্টিভ করলে তুলনা দেখা যাবে।")}</p></div></div><Button onClick={onOpenAdmission} variant="outline" className="min-h-10 rounded-xl border-[#6d4ab7] text-[#6d4ab7]">{copy("View admission tracks", "ভর্তি ট্র্যাক দেখো")}</Button></div></section>;
  const item = comparable ?? reviewed;
  const displayName = [item.institution, item.unit || item.title].filter(Boolean).join(" · ");
  const gapPositive = (item.gap ?? 0) >= 0;
  return <section className="rounded-[24px] border border-[#e7ddfb] bg-[#fbf9ff] p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#6d4ab7] text-white"><Trophy size={19} /></span><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#6d4ab7]">{copy("ADMISSION SCORE BENCHMARK", "ভর্তি স্কোর বেঞ্চমার্ক")}</p><h2 className="mt-1 font-display text-xl font-extrabold text-[#071d33]">{displayName}</h2><p className="mt-1 text-xs leading-5 text-slate-600">{copy(`Recorded ${item.session ?? "prior-year"} cut mark on a ${item.officialMaxMarks}-mark official scale.`, `${item.session ?? "আগের বছর"} রেকর্ড করা কাট মার্ক ${item.officialMaxMarks} মার্কের অফিসিয়াল স্কেলে।`)}</p></div></div>{item.sourceUrl && <a href={item.sourceUrl} target="_blank" rel="noreferrer" className="text-xs font-bold text-[#5a3f96] underline underline-offset-4">{copy("Review source", "সোর্স দেখো")}</a>}</div>{item.latestAttempt ? <div className="mt-5 grid gap-3 sm:grid-cols-3"><BenchmarkMetric label={copy("Your compatible mock", "তোমার কম্প্যাটিবল মক")} value={`${item.latestAttempt.score}/${item.latestAttempt.maxMarks}`} tone="bg-white text-[#071d33]" /><BenchmarkMetric label={copy("Recorded cut mark", "রেকর্ড করা কাট মার্ক")} value={`${item.cutMark}/${item.officialMaxMarks}`} tone="bg-white text-[#071d33]" /><BenchmarkMetric label={gapPositive ? copy("Above cut mark", "কাট মার্কের উপরে") : copy("Gap to cut mark", "কাট মার্কে ব্যবধান")} value={`${gapPositive ? "+" : ""}${item.gap}`} tone={gapPositive ? "bg-[#e9fbf7] text-[#087b6c]" : "bg-[#fff5e4] text-[#a45708]"} /></div> : <div className="mt-5 rounded-2xl bg-white p-4 text-sm leading-6 text-slate-600">{copy(`Complete a saved ${item.officialMaxMarks}-mark ${displayName} mock on the matching score scale to unlock this comparison. Short practice sets are not compared to a full cut mark.`, `${item.officialMaxMarks} মার্কের ${displayName} মক মিল থাকা স্কোর স্কেলে সম্পন্ন করলেই তুলনা চালু হবে। ছোট প্র্যাকটিস সেটকে পূর্ণ কাট মার্কের সাথে তুলনা করা হয় না।`)}</div>}<p className="mt-4 text-xs leading-5 text-slate-500">{copy("This is a historical score context, not an eligibility prediction or admission guarantee.", "এটি ঐতিহাসিক স্কোর কনটেক্সট; যোগ্যতা পূর্বাভাস বা ভর্তি নিশ্চয়তা নয়।")}</p></section>;
}
function BenchmarkMetric({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className={`rounded-2xl p-4 ${tone}`}><p className="text-xl font-extrabold">{value}</p><p className="mt-1 text-xs font-semibold opacity-75">{label}</p></div>; }
