import type { Language } from "@/components/PlatformShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Loader2, Users } from "lucide-react";
import { toast } from "sonner";

export function AdminLiveRoomManagement({ language }: { language: Language }) {
  const copy = (en: string, bn: string) => language === "bn" ? bn : en;
  const utils = trpc.useUtils();
  const rooms = trpc.liveExam.adminList.useQuery(undefined, { refetchInterval: 5_000 });
  const close = trpc.liveExam.close.useMutation({ onSuccess: result => { toast.success(copy(`Room closed; ${result.finalizedCount} active attempt(s) finalized.`, `রুম বন্ধ; ${result.finalizedCount}টি সক্রিয় চেষ্টা চূড়ান্ত করা হয়েছে।`)); utils.liveExam.adminList.invalidate(); utils.liveExam.list.invalidate(); }, onError: error => toast.error(error.message) });
  return <section className="rounded-[24px] border border-[#f2d4c9] bg-[#fffaf8] p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#c2492c]">{copy("ROOM MANAGEMENT", "রুম ম্যানেজমেন্ট")}</p><h2 className="mt-1 font-display text-xl font-extrabold text-[#071d33]">{copy("Manage live room status", "লাইভ রুমের স্ট্যাটাস ম্যানেজ করো")}</h2></div><span className="rounded-xl bg-white px-3 py-2 text-xs font-bold text-slate-500">{rooms.data?.length ?? 0} {copy("records", "রেকর্ড")}</span></div>{rooms.isLoading ? <div className="mt-4 flex h-20 items-center justify-center rounded-xl bg-white text-sm text-slate-500"><Loader2 className="mr-2 animate-spin" size={16} />{copy("Loading rooms…", "রুম লোড হচ্ছে…")}</div> : rooms.error ? <div className="mt-4 rounded-xl bg-white p-4 text-center"><AlertTriangle className="mx-auto text-[#b86b09]" size={20} /><p className="mt-2 text-xs text-slate-600">{rooms.error.message}</p><Button onClick={() => rooms.refetch()} className="mt-3 min-h-10 rounded-lg bg-[#071d33]">{copy("Retry", "আবার চেষ্টা")}</Button></div> : rooms.data?.length ? <div className="mt-4 space-y-2">{rooms.data.slice(0, 12).map(room => <article key={room.id} className="flex flex-wrap items-center gap-2 rounded-xl bg-white p-3 text-xs"><span className={`rounded-full px-2 py-1 font-bold ${room.status === "live" ? "bg-[#e9fbf7] text-[#087b6c]" : room.status === "scheduled" ? "bg-[#eef3ff] text-[#315bb3]" : "bg-slate-100 text-slate-500"}`}>{room.status === "live" ? copy("LIVE", "লাইভ") : room.status === "scheduled" ? copy("SCHEDULED", "শিডিউলড") : copy("CLOSED", "বন্ধ")}</span><strong className="min-w-28 flex-1 text-[#071d33]">{room.title}</strong><span className="text-slate-500"><Users className="mr-1 inline" size={13} />{room.participantCount}</span><span className="text-slate-500">{new Date(room.startsAt).toLocaleString(language === "bn" ? "bn-BD" : "en-GB", { dateStyle: "short", timeStyle: "short" })}</span>{["scheduled", "live"].includes(room.status) && <Button disabled={close.isPending} onClick={() => { if (window.confirm(copy(`Close “${room.title}” now? Active attempts will be finalized.`, `“${room.title}” এখন বন্ধ করবে? সক্রিয় চেষ্টা চূড়ান্ত করা হবে।`))) close.mutate({ roomId: room.id }); }} variant="outline" className="min-h-9 rounded-lg border-[#c2492c] px-3 text-[#c2492c]">{copy("Close now", "এখন বন্ধ")}</Button>}</article>)}</div> : <p className="mt-4 rounded-xl bg-white p-4 text-xs text-slate-500">{copy("No rooms have been created yet.", "এখনও কোনো রুম তৈরি করা হয়নি।")}</p>}</section>;
}
