import type { Language } from "@/components/PlatformShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, BarChart3, CheckCircle2, EyeOff, ListChecks } from "lucide-react";
import { useMemo, useState } from "react";

export function LiveResultReview({ roomId, language }: { roomId: number; language: Language }) {
  const copy = (en: string, bn: string) => language === "bn" ? bn : en;
  const [incorrectOnly, setIncorrectOnly] = useState(false);
  const review = trpc.liveExam.result.useQuery({ roomId });
  if (review.isLoading) return <section className="h-56 animate-pulse rounded-[24px] bg-white" />;
  if (review.error || !review.data) return <section className="rounded-[24px] bg-white p-6 text-center shadow-sm"><AlertTriangle className="mx-auto text-[#b86b09]" /><p className="mt-3 text-sm text-slate-600">{review.error?.message ?? copy("Result is not available yet.", "ফলাফল এখনও পাওয়া যাচ্ছে না।")}</p><Button onClick={() => review.refetch()} className="mt-4 rounded-xl bg-[#071d33]">{copy("Try again", "আবার চেষ্টা করো")}</Button></section>;
  const { participant, result, myRank, subjectAccuracy } = review.data;
  const answers = useMemo(() => incorrectOnly ? result.answers.filter(answer => !answer.isCorrect) : result.answers, [incorrectOnly, result.answers]);
  const incorrectCount = result.answers.filter(answer => !answer.isCorrect).length;
  return <section className="rounded-[24px] bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#088a78]">{copy("YOUR LIVE RESULT", "তোমার লাইভ ফলাফল")}</p><h2 className="mt-1 font-display text-2xl font-extrabold text-[#071d33]">{copy("Review answers. Target weak subjects.", "উত্তর রিভিউ করো। দুর্বল বিষয় লক্ষ্য করো।")}</h2></div><div className="flex gap-2"><span className="rounded-xl bg-[#071d33] px-3 py-2 text-sm font-extrabold text-white">{copy("Score", "স্কোর")}: {participant.finalScore ?? result.attempt.score ?? "0"}</span>{myRank && <span className="rounded-xl bg-[#fff5e4] px-3 py-2 text-sm font-extrabold text-[#a85d00]">#{myRank}</span>}</div></div>
    <div className="mt-5 rounded-2xl bg-[#f5faf9] p-4"><div className="flex items-center gap-2"><BarChart3 size={18} className="text-[#087b6c]" /><h3 className="font-display text-base font-extrabold text-[#071d33]">{copy("Subject accuracy", "বিষয়ভিত্তিক নির্ভুলতা")}</h3></div>{subjectAccuracy.length ? <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{subjectAccuracy.map(item => <article key={item.subject} className="rounded-xl bg-white p-3 shadow-sm"><div className="flex items-start justify-between gap-2"><p className="line-clamp-1 text-sm font-bold text-[#071d33]">{item.subject}</p><span className={`rounded-lg px-2 py-1 text-xs font-extrabold ${item.accuracy >= 70 ? "bg-[#e9fbf7] text-[#087b6c]" : item.accuracy >= 40 ? "bg-[#fff5e4] text-[#a85d00]" : "bg-[#fff0eb] text-[#c2492c]"}`}>{item.accuracy}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.accuracy >= 70 ? "bg-[#16b89b]" : item.accuracy >= 40 ? "bg-[#e5a523]" : "bg-[#d65a3a]"}`} style={{ width: `${item.accuracy}%` }} /></div><p className="mt-2 text-xs text-slate-500">{item.correct}/{item.total} {copy("correct", "সঠিক")}</p></article>)}</div> : <p className="mt-3 text-xs text-slate-500">{copy("Subject insight will appear once answers are available.", "উত্তর পাওয়া গেলে বিষয়ভিত্তিক ইনসাইট দেখা যাবে।")}</p>}</div>
    <div className="mt-5 flex flex-col justify-between gap-3 rounded-xl border border-slate-100 p-3 sm:flex-row sm:items-center"><div className="flex items-center gap-2 text-sm font-semibold text-[#071d33]"><ListChecks size={17} className="text-[#087b6c]" />{incorrectOnly ? copy(`${incorrectCount} incorrect answer${incorrectCount === 1 ? "" : "s"} shown`, `${incorrectCount}টি ভুল উত্তর দেখা যাচ্ছে`) : copy(`${result.answers.length} submitted answers`, `${result.answers.length}টি জমা দেওয়া উত্তর`)}</div><Button onClick={() => setIncorrectOnly(value => !value)} variant={incorrectOnly ? "default" : "outline"} className={`min-h-11 rounded-xl ${incorrectOnly ? "bg-[#c2492c] hover:bg-[#ad3d25]" : "border-[#c2492c] text-[#c2492c]"}`}><EyeOff size={16} />{incorrectOnly ? copy("Show all answers", "সব উত্তর দেখো") : copy("Only incorrect answers", "শুধু ভুল উত্তর")}</Button></div>
    <div className="mt-4 space-y-3">{answers.length ? answers.map((answer, index) => <article key={answer.questionId} className={`rounded-xl border p-4 ${answer.isCorrect ? "border-[#bdeadd] bg-[#f7fffd]" : "border-[#f4d1c7] bg-[#fffaf8]"}`}><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs font-bold text-slate-500">{index + 1}. {answer.subject} · {answer.chapter ?? copy("General", "সাধারণ")}</span><span className={`flex items-center gap-1 text-xs font-extrabold ${answer.isCorrect ? "text-[#087b6c]" : "text-[#c2492c]"}`}>{answer.isCorrect ? <CheckCircle2 size={14} /> : <AlertTriangle size={14} />}{answer.isCorrect ? copy("Correct", "সঠিক") : copy("Incorrect", "ভুল")} · {answer.awardedMarks ?? "0"}</span></div><p className="mt-2 text-sm font-bold leading-6 text-[#071d33]">{answer.prompt}</p><div className="mt-3 rounded-lg bg-white/75 p-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#087b6c]">{copy("EXPLANATION", "ব্যাখ্যা")}</p><p className="mt-1 text-xs leading-5 text-slate-600">{answer.explanation ?? copy("An approved explanation has not been published for this question yet.", "এই প্রশ্নের অনুমোদিত ব্যাখ্যা এখনও প্রকাশিত হয়নি।")}</p></div></article>) : <div className="rounded-xl bg-[#e9fbf7] p-5 text-center text-sm font-semibold text-[#087b6c]"><CheckCircle2 className="mx-auto mb-2" size={22} />{copy("Excellent—there are no incorrect answers in this attempt.", "চমৎকার—এই চেষ্টায় কোনো ভুল উত্তর নেই।")}</div>}</div>
  </section>;
}
